// Words containing 'mstr'
let words = [
  "hamster",
  "mønsterborger",
  "halmstrå",
  "omstrukturering",
  "statsminister",
  "femstjernet",
  "Amsterdam",
  "monstrøs",
  "feminister",
  "medium str.",
  "smagsforstyrrelse",
  "medister",
  "salmestrofe",
  "webmaster",
  "toastmaster",
  "tremaster",
  "sprechstallmeister",
  "madrester",
  "kriminalregister",
  "flammekaster",
  "rå muskelstyrke",
  "musetrappe",
  "maestro",
  "Manchester",
  "målstreg",
  "rumstationer",
  "mistroisk",
  "atmosfærisk tryk",
  "himstregims",
  "varmestuer",
  "kampstrategi",
  "musikterapi",
  "lommestrikkeri",
  "skumstribe",
  "dampskibstransport",
  "demonstrant",
  "komposterende",
];
